server:
  port: 8085



swagger:
  enable: true
  application-name: plantary系统API说明
  application-version: 1.0
  application-description: springfox swagger 3.0整合Demo
  try-host: http://localhost:${server.port}

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher